// This file defines the User model for MongoDB using Mongoose.
// It includes fields for different user roles and their specific attributes.

const mongoose = require('mongoose');

const userSchema = new mongoose.Schema({
    name: { type: String, required: true }, // Full name of the user.
    email: { type: String, required: true, unique: true, index: true }, // Email address, must be unique.
    password: { type: String, required: true }, // Hashed password for authentication.
    role: {
        type: String,
        enum: ['admin', 'doctor', 'patient'], // User roles supported by the system.
        default: 'patient',
        required: true
    },
    // Indicates whether the user's email is verified.
    isEmailVerified: { type: Boolean, default: false },
    emailVerificationOTP: { type: String }, // OTP for email verification.
    otpExpiry: { type: Date }, // Expiry time for the OTP.

    // Fields specific to doctors for simplified registration.
    doctorInfo: {
        isVerified: { type: Boolean, default: true } // Doctors are auto-verified by default.
    },

    // Fields specific to patients.
    patientInfo: {
        dateOfBirth: { type: Date }, // Patient's date of birth.
        gender: { type: String }, // Gender of the patient.
        medicalHistory: [String], // List of medical history records.
        serial: { type: String, unique: true, sparse: true } // Unique serial number for patients.
    },

    // Reference to the doctor assigned to the patient.
    assignedDoctor: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User'
    },

    // List of patients assigned to a doctor.
    assignedPatients: [{
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User'
    }],

    // Fields for Google authentication.
    googleId: { type: String }, // Google account ID.
    picture: { type: String }, // Profile picture URL.
    createdAt: {
        type: Date,
        default: Date.now // Timestamp when the user was created.
    },
    lastActive: {
        type: Date,
        default: Date.now // Timestamp of the user's last activity.
    },
    hospital: String, // Name of the hospital associated with the user.
    lastScanDate: Date, // Date of the user's last scan.
    status: {
        type: String,
        enum: ['active', 'inactive', 'suspended'], // Current status of the user.
        default: 'active'
    },
    resetToken: { type: String }, // Token for password reset.
    resetTokenExpiry: { type: Date }, // Expiry time for the reset token.
    meta: {
        reportCount: { type: Number, default: 0 }, // Total number of reports generated by the user.
        successfulScans: { type: Number, default: 0 }, // Count of successful scans.
        failedScans: { type: Number, default: 0 } // Count of failed scans.
    }
});

// Add compound indexes to optimize filtering and sorting queries.
userSchema.index({ role: 1, status: 1 });
userSchema.index({ role: 1, createdAt: -1 });
userSchema.index({ 'doctorInfo.isVerified': 1, role: 1 });

// Virtual field to provide a user-friendly description of the user's role.
userSchema.virtual('userType').get(function() {
    if (this.role === 'doctor') {
        return `Doctor - ${this.doctorInfo.specialty || 'Unspecified'}`;
    } else if (this.role === 'patient') {
        return 'Patient';
    } else if (this.role === 'admin') {
        return 'Admin';
    }
    return this.role;
});

// Ensure virtual fields are included in JSON and object outputs.
userSchema.set('toJSON', { virtuals: true });
userSchema.set('toObject', { virtuals: true });

module.exports = mongoose.model('User', userSchema);
